/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import reports.relPaciente;
import javax.swing.JOptionPane;

/**
 *
 * @author rui
 */
public class frmDesktop extends javax.swing.JFrame {

    /**
     * Creates new form frmDesktop
     */
    public frmDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        cadPaciente = new javax.swing.JMenuItem();
        cadFuncionario = new javax.swing.JMenuItem();
        cadPlano = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        relPaciente = new javax.swing.JMenu();
        listPaciente = new javax.swing.JMenuItem();
        ficPaciente = new javax.swing.JMenuItem();
        ficProntuario = new javax.swing.JMenuItem();
        relFuncionario = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop.getContentPane());
        desktop.getContentPane().setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AREA DE TRABALHO");

        mnCadastro.setText("CADASTROS");
        mnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroActionPerformed(evt);
            }
        });

        cadPaciente.setText("PACIENTE");
        cadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPacienteActionPerformed(evt);
            }
        });
        mnCadastro.add(cadPaciente);

        cadFuncionario.setText("FUNCIONARIO");
        mnCadastro.add(cadFuncionario);

        cadPlano.setText("PLANO");
        cadPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPlanoActionPerformed(evt);
            }
        });
        mnCadastro.add(cadPlano);

        jMenuBar1.add(mnCadastro);

        mnRelatorio.setText("RELATORIOS");

        relPaciente.setText("PACIENTE");
        relPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relPacienteActionPerformed(evt);
            }
        });

        listPaciente.setText("LISTA DE PACIENTES");
        listPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPacienteActionPerformed(evt);
            }
        });
        relPaciente.add(listPaciente);

        ficPaciente.setText("FICHA DO PACIENTE");
        relPaciente.add(ficPaciente);

        ficProntuario.setText("PRONTUARIO");
        relPaciente.add(ficProntuario);

        mnRelatorio.add(relPaciente);

        relFuncionario.setText("FUNCIONARIO");

        jMenuItem2.setText("LISTA DE FUNCIONARIOS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        relFuncionario.add(jMenuItem2);

        jMenuItem3.setText("FICHA DO FUNCIONARIO");
        relFuncionario.add(jMenuItem3);

        jMenuItem4.setText("AGENDA DO FUNCIONARIO");
        relFuncionario.add(jMenuItem4);

        mnRelatorio.add(relFuncionario);

        jMenuBar1.add(mnRelatorio);

        mnSair.setText("SAIR");
        mnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void relPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relPacienteActionPerformed

    private void cadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPacienteActionPerformed
        // TODO add your handling code here:

        try {
            new frmPessoa().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cadPacienteActionPerformed

    private void listPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPacienteActionPerformed
        // TODO add your handling code here:

        try {
            new relPaciente().listPaciente();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_listPacienteActionPerformed

    private void mnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSairMouseClicked

    private void cadPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPlanoActionPerformed
        // TODO add your handling code here:
        try {
            new frmPlano().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cadPlanoActionPerformed

    private void mnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCadastroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem cadFuncionario;
    public static javax.swing.JMenuItem cadPaciente;
    public static javax.swing.JMenuItem cadPlano;
    public static javax.swing.JFrame desktop;
    public static javax.swing.JMenuItem ficPaciente;
    public static javax.swing.JMenuItem ficProntuario;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JMenuItem listPaciente;
    public static javax.swing.JMenu mnCadastro;
    public static javax.swing.JMenu mnRelatorio;
    public static javax.swing.JMenu mnSair;
    public static javax.swing.JMenu relFuncionario;
    public static javax.swing.JMenu relPaciente;
    // End of variables declaration//GEN-END:variables
}
